#pragma once

#include "config.h"
#include "ilogger.h"

#include <queue.hpp>
#include <thread.hpp>

#include <array>
#include <cstdint>

namespace rtos = cpp_freertos;

struct pmbus_cmd_info {
    const char* name;
    uint8_t code;
    uint8_t dir;
    bool realized;
    bool status;
};

class pmbus_logger_thread final : rtos::Thread {
  public:
    pmbus_logger_thread();
    pmbus_logger_thread(const pmbus_logger_thread&) = delete;
    pmbus_logger_thread& operator=(const pmbus_logger_thread&) = delete;
    pmbus_logger_thread(pmbus_logger_thread&&) = delete;
    pmbus_logger_thread& operator=(pmbus_logger_thread&&) = delete;
    ~pmbus_logger_thread() = default;

    void start();
    bool log(pmbus_cmd_info* pcmd);

  private:
    void Run() override;

    rtos::Queue buff_{pmbus_logger_queue_size, sizeof(pmbus_cmd_info)};
    ilogger& logger_;
};

constexpr std::array pmbus_cmd_names{
        "PAGE",
        "OPERATION",
        "ON_OFF_CONFIG",
        "CLEAR_FAULTS",
        "PHASE",
        "PAGE_PLUS_WRITE",
        "PAGE_PLUS_READ",
        "ZONE_CONFIG",
        "ZONE_ACTIVE",
        "RESERVED_09",
        "RESERVED_0A",
        "RESERVED_0B",
        "RESERVED_0C",
        "RESERVED_0D",
        "RESERVED_0E",
        "RESERVED_0F",
        "WRITE_PROTECT",
        "STORE_DEFAULT_ALL",
        "RESTORE_DEFAULT_ALL",
        "STORE_DEFAULT_CODE",
        "RESTORE_DEFAULT_CODE",
        "STORE_USER_ALL",
        "RESTORE_USER_ALL",
        "STORE_USER_CODE",
        "RESTORE_USER_CODE",
        "CAPABILITY",
        "QUERY",
        "SMBALERT_MASK",
        "RESERVED_1C",
        "RESERVED_1D",
        "RESERVED_1E",
        "RESERVED_1F",
        "VOUT_MODE",
        "VOUT_COMMAND",
        "VOUT_TRIM",
        "VOUT_CAL_OFFSET",
        "VOUT_MAX",
        "VOUT_MARGIN_HIGH",
        "VOUT_MARGIN_LOW",
        "VOUT_TRANSITION_RATE",
        "VOUT_DROOP",
        "VOUT_SCALE_LOOP",
        "VOUT_SCALE_MONITOR",
        "VOUT_MIN",
        "RESERVED_2C",
        "RESERVED_2D",
        "RESERVED_2E",
        "RESERVED_2F",
        "COEFFICIENTS",
        "POUT_MAX",
        "MAX_DUTY",
        "FREQUENCY_SWITCH",
        "POWER_MODE",
        "VIN_ON",
        "VIN_OFF",
        "INTERLEAVE",
        "IOUT_CAL_GAIN",
        "IOUT_CAL_OFFSET",
        "FAN_CONFIG_1_2",
        "FAN_COMMAND_1",
        "FAN_COMMAND_2",
        "FAN_CONFIG_3_4",
        "FAN_COMMAND_3",
        "FAN_COMMAND_4",
        "VOUT_OV_FAULT_LIMIT",
        "VOUT_OV_FAULT_RESPONSE",
        "VOUT_OV_WARN_LIMIT",
        "VOUT_UV_WARN_LIMIT",
        "VOUT_UV_FAULT_LIMIT",
        "VOUT_UV_FAULT_RESPONSE",
        "IOUT_OC_FAULT_LIMIT",
        "IOUT_OC_FAULT_RESPONSE",
        "IOUT_OC_LV_FAULT_LIMIT",
        "IOUT_OC_LV_FAULT_RESPONSE",
        "IOUT_OC_WARN_LIMIT",
        "IOUT_UC_FAULT_LIMIT",
        "IOUT_UC_FAULT_RESPONSE",
        "RESERVED_4D",
        "RESERVED_4E",
        "OT_FAULT_LIMIT",
        "OT_FAULT_RESPONSE",
        "OT_WARN_LIMIT",
        "UT_WARN_LIMIT",
        "UT_FAULT_LIMIT",
        "UT_FAULT_RESPONSE",
        "VIN_OV_FAULT_LIMIT",
        "VIN_OV_FAULT_RESPONSE",
        "VIN_OV_WARN_LIMIT",
        "VIN_UV_WARN_LIMIT",
        "VIN_UV_FAULT_LIMIT",
        "VIN_UV_FAULT_RESPONSE",
        "IIN_OC_FAULT_LIMIT",
        "IIN_OC_FAULT_RESPONSE",
        "IIN_OC_WARN_LIMIT",
        "POWER_GOOD_ON",
        "POWER_GOOD_OFF",
        "TON_DELAY",
        "TON_RISE",
        "TON_MAX_FAULT_LIMIT",
        "TON_MAX_FAULT_RESPONSE",
        "TOFF_DELAY",
        "TOFF_FALL",
        "TOFF_MAX_WARN_LIMIT",
        "RESERVED_67",
        "POUT_OP_FAULT_LIMIT",
        "POUT_OP_FAULT_RESPONSE",
        "POUT_OP_WARN_LIMIT",
        "PIN_OP_WARN_LIMIT",
        "RESERVED_6C",
        "RESERVED_6D",
        "RESERVED_6E",
        "RESERVED_6F",
        "RESERVED_70",
        "RESERVED_71",
        "RESERVED_72",
        "RESERVED_73",
        "RESERVED_74",
        "RESERVED_75",
        "RESERVED_76",
        "RESERVED_77",
        "STATUS_BYTE",
        "STATUS_WORD",
        "STATUS_VOUT",
        "STATUS_IOUT",
        "STATUS_INPUT",
        "STATUS_TEMPERATURE",
        "STATUS_CML",
        "STATUS_OTHER",
        "STATUS_MFR_SPECIFIC",
        "STATUS_FANS_1_2",
        "STATUS_FANS_3_4",
        "READ_KWH_IN",
        "READ_KWH_OUT",
        "READ_KWH_CONFIG",
        "READ_EIN",
        "READ_EOUT",
        "READ_VIN",
        "READ_IIN",
        "READ_VCAP",
        "READ_VOUT",
        "READ_IOUT",
        "READ_TEMPERATURE_1",
        "READ_TEMPERATURE_2",
        "READ_TEMPERATURE_3",
        "READ_FAN_SPEED_1",
        "READ_FAN_SPEED_2",
        "READ_FAN_SPEED_3",
        "READ_FAN_SPEED_4",
        "READ_DUTY_CYCLE",
        "READ_FREQUENCY",
        "READ_POUT",
        "READ_PIN",
        "PMBUS_REVISION",
        "MFR_ID",
        "MFR_MODEL",
        "MFR_REVISION",
        "MFR_LOCATION",
        "MFR_DATE",
        "MFR_SERIAL",
        "APP_PROFILE_SUPPORT",
        "MFR_VIN_MIN",
        "MFR_VIN_MAX",
        "MFR_IIN_MAX",
        "MFR_PIN_MAX",
        "MFR_VOUT_MIN",
        "MFR_VOUT_MAX",
        "MFR_IOUT_MAX",
        "MFR_POUT_MAX",
        "MFR_TAMBIENT_MAX",
        "MFR_TAMBIENT_MIN",
        "MFR_EFFICIENCY_LL",
        "MFR_EFFICIENCY_HL",
        "MFR_PIN_ACCURACY",
        "IC_DEVICE_ID",
        "IC_DEVICE_REV",
        "RESERVED_AF",
        "USER_DATA_00",
        "USER_DATA_01",
        "USER_DATA_02",
        "USER_DATA_03",
        "USER_DATA_04",
        "USER_DATA_05",
        "USER_DATA_06",
        "USER_DATA_07",
        "USER_DATA_08",
        "USER_DATA_09",
        "USER_DATA_10",
        "USER_DATA_11",
        "USER_DATA_12",
        "USER_DATA_13",
        "USER_DATA_14",
        "USER_DATA_15",
        "MFR_MAX_TEMP_1",
        "MFR_MAX_TEMP_2",
        "MFR_MAX_TEMP_3",
        "RESERVED_C3",
        "MFR_SPECIFIC_C4",
        "MFR_SPECIFIC_C5",
        "MFR_SPECIFIC_C6",
        "MFR_SPECIFIC_C7",
        "MFR_SPECIFIC_C8",
        "MFR_SPECIFIC_C9",
        "MFR_SPECIFIC_CA",
        "MFR_SPECIFIC_CB",
        "MFR_SPECIFIC_CC",
        "MFR_SPECIFIC_CD",
        "MFR_SPECIFIC_CE",
        "MFR_SPECIFIC_CF",
        "MFR_SPECIFIC_D0",
        "MFR_SPECIFIC_D1",
        "MFR_SPECIFIC_D2",
        "MFR_SPECIFIC_D3",
        "MFR_SPECIFIC_D4",
        "MFR_SPECIFIC_D5",
        "MFR_SPECIFIC_D6",
        "MFR_SPECIFIC_D7",
        "MFR_SPECIFIC_D8",
        "MFR_SPECIFIC_D9",
        "MFR_SPECIFIC_DA",
        "MFR_SPECIFIC_DB",
        "MFR_SPECIFIC_DC",
        "MFR_SPECIFIC_DD",
        "MFR_SPECIFIC_DE",
        "MFR_SPECIFIC_DF",
        "MFR_SPECIFIC_E0",
        "MFR_SPECIFIC_E1",
        "MFR_SPECIFIC_E2",
        "MFR_SPECIFIC_E3",
        "MFR_SPECIFIC_E4",
        "MFR_SPECIFIC_E5",
        "MFR_SPECIFIC_E6",
        "MFR_SPECIFIC_E7",
        "MFR_SPECIFIC_E8",
        "MFR_SPECIFIC_E9",
        "MFR_SPECIFIC_EA",
        "MFR_SPECIFIC_EB",
        "MFR_SPECIFIC_EC",
        "MFR_SPECIFIC_ED",
        "MFR_SPECIFIC_EE",
        "MFR_SPECIFIC_EF",
        "MFR_SPECIFIC_F0",
        "MFR_SPECIFIC_F1",
        "MFR_SPECIFIC_F2",
        "MFR_SPECIFIC_F3",
        "MFR_SPECIFIC_F4",
        "MFR_SPECIFIC_F5",
        "MFR_SPECIFIC_F6",
        "MFR_SPECIFIC_F7",
        "MFR_SPECIFIC_F8",
        "MFR_SPECIFIC_F9",
        "MFR_SPECIFIC_FA",
        "MFR_SPECIFIC_FB",
        "MFR_SPECIFIC_FC",
        "MFR_SPECIFIC_FD",
        "MFR_SPECIFIC_COMMAND_EXT",
        "PMBUS_CMD_PMBUS_COMMAND_EXT",
};
